### ISSUE TITLE
Do nothing if testing is disabled

### ISSUE THREAD

**Issue by jalada** [pixielabs/cavy#1]

**Comment by TGPSKI** [comment]
https://github.com/pixielabs/cavy/pull/20

This PR shows an example on how to implement this feature.

**Comment by siddarthpatel** [comment]
@TGPSKI Hey I see you have experience with Cavy. Could you please tell me how I could disable the resetting of the app every time a test spec is completed? Thanks.

**Comment by Megislava** [comment]
Hi all!
I possibly have the same question as some others. How can I develop w/o cavy doing tests? I have already separated production from cavy but I need to **sepate** testing the app with cavy and developing the app.
I hope that my question is understandable :)

**Comment by jalada** [comment]
@Megislava you have a couple of options. You can have two `index.test.js` and `index.js` files, and use some npm scripts to swap them in and out before running Cavy. Or you could have an entirely separate iOS/Android app within your XCode/Android Studio configuration which have different `index.js` entry files.

Does that make sense?

**Comment by AbigailMcP** [comment]
@Megislava - if you're using [cavy-cli](https://github.com/pixielabs/cavy-cli) to run your tests, it now checks for the presence of an `index.test.js` file and, if present, uses this as the entry point to your app for testing purposes.

If you move all your test setup into `index.test.js`, you can then remove Cavy completely from `index.js`.

Hope this helps! I'm going to close this issue, but please let me know if you have any further comments / issues.
