### ISSUE TITLE
Any Way to Just Tap a Referenced Component at an X,Y Coordinate?

### ISSUE THREAD

**Issue by reggie3** [pixielabs/cavy#105]
Is there anyway to just tap a component at a given X,Y coordinate?  This would be useful in testing applications that rely on maps.

**Comment by reggie3** [comment]
This functionality would be the same as tapAtPoint in Detox https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#tapatpoint

**Comment by AbigailMcP** [comment]
Hey @reggie3! Since Cavy is JavaScript only, this isn't something that we can support as it would require a native component. We'll keep this in mind for the future, but it's not something that is currently on the roadmap for now.
