### ISSUE TITLE
Clearer documentation for integrating with cavy-cli

### ISSUE THREAD

**Issue by jalada** [pixielabs/cavy#106]
> In case you missed it in the Cavy docs (as I did), when using cavy-cli, you’ll want to set the Tester’s sendReport prop to true.

[Source](https://spin.atomicobject.com/2019/02/11/react-native-testing-cavy/?utm_source=twitter-ao&utm_medium=social&utm_campaign=react-native-testing-cavy)

**Comment by AbigailMcP** [comment]
Addressed in PR #115
