### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by jalada** [pixielabs/cavy#108]
> If you’re using TypeScript, you’ll find that there are currently no type definitions. This means you’ll probably want to provide your own type definitions. Because Cavy’s very simple, this shouldn’t be too hard, but it does add overhead.

[Source](https://spin.atomicobject.com/2019/02/11/react-native-testing-cavy/?utm_source=twitter-ao&utm_medium=social&utm_campaign=react-native-testing-cavy)

**Comment by tyler-hoffman** [comment]
Hey @jalada - I'll have a pull request in for this shortly.

A question for you, though: I think it may make sense to move public comments from the function implementations in .js files to the function declarations in the .d.ts. Does that seem right to you?

**Comment by jalada** [comment]
Hmm, I think I'd like to keep the comments in the JS. It'll keep the code reading experience simpler.

**Comment by tyler-hoffman** [comment]
Moved PR to definitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33348

**Comment by jalada** [comment]
Thanks @tyler-hoffman! Once the PR is merged we'll add some notes to the README about it.

**Comment by juangamnik** [comment]
Hey, does this mean, that there will be typescript support soon?

**Comment by jalada** [comment]
@juangamnik @types have been merged in: https://www.npmjs.com/package/@types/cavy.

We'll add something to the README.
