### ISSUE TITLE
Support a native reporter so that JS test results can be captured by a native test framework.

### ISSUE THREAD

**Issue by jalada** [pixielabs/cavy#119]
[WatermelonDB](https://github.com/Nozbe/WatermelonDB/) use Cavy to test some React Native code within JavaScript, but they've written their own native module to support passing Cavy test results to XCTest / JUnit.

We've always wanted to support additional reporter modules as per discussion in #21 and #16. We thought it would be a requirement for `cavy-cli`, but wasn't, but is still part of our roadmap for Cavy.

We will support this style of native reporting upstream, probably through an additional package (perhaps called `cavy-reporter-native`), so that others can more easily run Cavy tests within a larger native test framework (e.g. XCTest & JUnit) in the same style as WatermelonDB.

The work done so far:

1. [Changes made to Cavy](https://github.com/pixielabs/cavy/compare/master...Nozbe:master) to support a custom reporter.
2. [WatermelonDB's native module in iOS](https://github.com/Nozbe/WatermelonDB/blob/master/native/iosTest/WatermelonTester/BridgeTestReporter.swift) and [Android](https://github.com/Nozbe/WatermelonDB/blob/master/native/androidTest/app/src/main/java/com/nozbe/watermelonTest/BridgeTestReporter.kt).
4. [WatermelonDB's native test in iOS](https://github.com/Nozbe/WatermelonDB/blob/master/native/iosTest/WatermelonTesterTests/BridgeTests.swift) and [Android](https://github.com/Nozbe/WatermelonDB/blob/master/native/androidTest/app/src/androidTest/java/com/nozbe/watermelonTest/BridgeTest.kt).

Thanks @radex and [Nozbe](https://github.com/Nozbe) for your work so far on this! 🙏

**Comment by AbigailMcP** [comment]
Released [Cavy Native Reporter](https://github.com/pixielabs/cavy-native-reporter)! Thanks again to @radex and Nozbe for your help with this 🙏 

Cavy's custom reporting functionality added in PR #126 .
