### ISSUE TITLE
Cavy-cli leaves test hanging

### ISSUE THREAD

**Issue by mikeatblockx** [pixielabs/cavy#122]
In local testing, here's what my index.test.js file looks like:

```
import { AppRegistry } from 'react-native';
import React from 'react';
import { Tester, TestHookStore } from 'cavy';

import App from './app/App';
import { name as appName } from './app.json';
import WelcomeSpec from './specs/WelcomeSpec';

const testHookStore = new TestHookStore();

class TestWrapper extends React.Component {
  render() {
    return (
      <Tester specs={[WelcomeSpec]} store={testHookStore} sendReport={true}>
        <App />
      </Tester>
    );
  }
```

After setting it up, I run `cavy run-ios`
It just hangs on:
```
cavy: react-native exited with code 0.
cavy: listening on port 8082 for test results...
```

If I have remote debugging setup, it shows the tests as passing, so I'm not sure what to do

**Comment by mikeatblockx** [comment]
Nevermind! I forget to use the `sendReport` prop

**Comment by AbigailMcP** [comment]
Glad you got this sorted @mikeatblockx. I'm going to make the `sendReport` prop more obvious in the README - a few people have had the same issue recently!

**Comment by mikeatblockx** [comment]
Thanks for the quick reply @AbigailMcP!
You've made a really great tool here, I was up and running in less than an hour

**Comment by MrHubble** [comment]
@AbigailMcP I'm also experiencing the behaviour where after I run `cavy run-ios` it hangs on:

```
cavy: react-native exited with code 0.
cavy: listening on port 8082 for test results...
```

I believe `sendReport` is now deprecated so that won't be the fix for me. Anything else you could suggest for debugging this?

Some sample code:

```
\\index.notest.js

import React, { Component } from 'react'
import { AppRegistry } from 'react-native'
import { Tester, TestHookStore } from 'cavy'
import ExampleSpec from './specs/exampleSpec'
import App from './app'

const testHookStore = new TestHookStore()

class AppWrapper extends Component {
  render() {
    return (
      <Tester specs={[ExampleSpec]} store={testHookStore}>
        <App />
      </Tester>
    )
  }
}

AppRegistry.registerComponent('myAppName', () => AppWrapper)
```

```
\\ exampleSpec.js

export default function (spec) {
  spec.describe('Logging in', () => {
    spec.it('works', async () => {
      await spec.press('Scene.AcceptButton')
    })
  })
}
```

```
\\ scene.js

import React, { Component } from 'react'
import {
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  Alert,
  Platform
} from 'react-native'
import { hook } from 'cavy'

class Scene extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.content}>
          <TouchableHighlight
            testID="acceptButton"
            ref={this.props.generateTestHook('Scene.AcceptButton')}
          >
            <Text style={styles.buttonText}>Accept</Text>
          </TouchableHighlight>
        </View>
      </View>
    )
  }
}

export default hook(Scene)
```

**Comment by AbigailMcP** [comment]
Hi @MrHubble , I can't see anything obviously incorrect in your code snippets... 

To help us narrow down the issue, could you let me know:

1. What version of Cavy and React Native are you using?
2. Is there any output from Cavy in your browser console when you run `cavy run-ios` and debug JS remotely?

**Comment by hanwencheng** [comment]
Got the same problem

>What version of Cavy and React Native are you using?

Does the version matters? I am using React Native `0.60.5`

When I set the `startDelay={10000}`, I did not see any delay of the application.

And thanks for the great library @AbigailMcP , it is my first day trying Cavy, probably another dumb question, will the `console.log` get logged in the devtool debugger? does the `console.assert` also works in the `beforeEach()`? since the test hangs here, I have no idea where will the logs appear.

**Comment by AbigailMcP** [comment]
Hey @hanwencheng ! Thanks for checking out Cavy :) and sorry it's taken me a while to get back to you.

`console.log` and `console.assert` will absolutely work in `beforeEach` (and elsewhere in your tests), and will be printed out to the React Native Debugger console.

Did you get any further with your issue with Cavy hanging? I released an update to Cavy CLI last week that fixed a bug for users with entry files other than `index.js` - does that apply to you?

**Comment by MrHubble** [comment]
This is what I get when I try to run the [sample app](https://github.com/pixielabs/cavy/tree/master/sample-app/CavyDirectory):

<img width="971" alt="Screen Shot 2019-11-15 at 3 52 53 pm" src="https://user-images.githubusercontent.com/2251631/68917869-25f2b600-07c0-11ea-9db8-2001baffeb6e.png">

I've followed the suggested steps (ie `watchman watch-del-all` and `rm -rf node_modules`).

**Comment by AbigailMcP** [comment]
Hmm... I don't think this is a Cavy issue. I've just tested and the sample app builds and runs fine for me (and in our CI).

I'd suggest re-cloning the repo and installing again, perhaps following the steps in our CircleCI config: https://github.com/pixielabs/cavy/blob/master/.circleci/config.yml
