### ISSUE TITLE
Support to add subtest reports within a single test: expose a function that does that

### ISSUE THREAD

**Issue by roydipti23** [pixielabs/cavy#134]
In this file
https://github.com/pixielabs/cavy/blob/5f815145475361a9c178b71ab082fa3b8fec5b8e/src/TestRunner.js#L67

As we are having report, we might have subtests report that we want to generate over the parent report; for a single test case.

We have this use case in our organisation, wherein one integration test flow invloves testing more that one page (SPA); and we need to generate a passed case for each page alongwith the final result ; for this a support is needed.

Recomended:

1. Have a class variable- this.subTestResults (an array)
2. expose a function that lets me add a sucess sub test in this array while running the test case

import hook from './src/hook';
import Tester from './src/Tester';
import TestHookStore from './src/TestHookStore';
import useCavy from './src/useCavy';
import wrap from './src/wrap';
import addSubTestCase from './src/wrap';

const Cavy = {
  hook,
  Tester,
  TestHookStore,
  useCavy,
  wrap,
  addSubTestCase
};

module.exports = Cavy;

**cavy/src**

_addSubTestCase.js_

import {addSubTestCase} from './TestRunner';
export default addSubTestCase;

**TestRunner.js**

let subTestResults = [];
export function addSubTestCase({successMsg}) {
   subTestResults.push({message: successMsg, passed: true});
}

export default class TestRunner {
 ...

    // Compile the report object.
    const report = {
      results: this.testResults,
      subResults: subTestResults,  // adding subtest results
      errorCount: this.errorCount,
      duration: duration
    }

  async runTest(scope, test) {
    await this.component.clearAsync();
    if (scope.beforeEach) { await scope.beforeEach.call(scope) };
    this.component.reRender();

    // Run the test, console logging the result.
    let { description, f } = test;
    try {
      subTestResults = []; // reset the value for each test case
      await f.call(scope);
      let successMsg = `${description}  ✅`;

      console.log(successMsg);
      this.testResults.push({message: successMsg, passed: true});
    } catch (e) {
      let errorMsg = `${description}  ❌\n   ${e.message}`;

      console.warn(errorMsg);
      this.testResults.push({message: errorMsg, passed: false});
      // Increase error count for reporting.
      this.errorCount += 1;
    }
  }
}

**Comment by roydipti23** [comment]
Let me know recommendations around the same; because this feature is very much needed for us to integrate cavy, since we have more that 4 pages navigation, and we need to generate the test success for each page.

We cannot test each navigation one by one, as this doesnt makes sense, and will also increase the test running time.

**Comment by roydipti23** [comment]
PR for the same : https://github.com/pixielabs/cavy/pull/135

**Comment by jalada** [comment]
Hello @roydipti23! Thanks for getting in touch, excited to hear you're trying to integrate Cavy.

I'm struggling to understand why you need this functionality though. I understand that you have one test case that is testing multiple pages at the same time. But why do you need separate success reports for parts of that test? If one part of the test fails, you'll know where during the test case it failed. And if it succeeds, you know they all succeeded.

Mid-way reporting of tests feels unusual for a test runner. Can you provide any examples of other test runners (e.g. RSpec, Jasmine, Jest) supporting this?

Are there any alternative approaches you evaluated before settling on this one?

**Comment by roydipti23** [comment]
Hi @jalada,

Yes i agree that if one part of the test fails, you'll know where during the test case it failed; but it usually breaks when a component is not found; and it gets difficult to retrace as to which part it failed.
Also if we have subtests reports, since multiple people are working on different pages of the same app, it gets easier to redirect/ align the person with the failed test case.
Our App (goibibo) involves a lot of business logics and few subtests are better to have, rather than having subsequent individual tests to test a sub feature.

It usually helps in case of failures.

I feel, it is a good to have optional feature.

**Comment by jalada** [comment]
OK, thanks for the background information @roydipti23! I'd like to tackle this a little differently:

> it gets difficult to retrace as to which part it failed.

This is something we can fix with some better error reporting, optional tagging of expectations with failure messages, and so on. Does that sound like an approach that would help?

**Comment by roydipti23** [comment]
I feel it might get tedius trying to make the developer add onto failure messages, also i dont see how you would achieve that; since it would be wrong to send parameters of messages to spec.exists (which is the most widely used one)

**Comment by jalada** [comment]
For now we're not planning on adding this to Cavy. I'm going to close this for now, but if you're arriving at this issue and think we should re-evaluate, please leave a comment!
