### ISSUE TITLE
Cavy not running in release build

### ISSUE THREAD

**Issue by roydipti23** [pixielabs/cavy#143]
If we have to integrate Cavy in our pre-production circle tests, it should generate results on the release build too.
Right now what i am facing is, Cavy Tests run only in debug mode; and not in normal flow.
Is there a turn around or solution for this?
This is a blocker for us to integrate cavy as pre-release, one round of test sanity needs to run on release build.

**Comment by jalada** [comment]
Hey @roydipti23, that's odd. There's no particular reason why Cavy doesn't run in release mode. Do you have any logs you can share?

**Comment by roydipti23** [comment]
@jalada just do it in emulator - do not do debug JS remotely
after invoking React Native, tests are not running. There are no logs produced. I can share with and without debug JS remotely cli report

**Comment by roydipti23** [comment]
in debug
<img width="971" alt="Screenshot 2019-07-30 at 12 50 32 PM" src="https://user-images.githubusercontent.com/29539247/62108877-bddb9b00-b2c8-11e9-9745-9a4d7715aca6.png">

in release
<img width="943" alt="Screenshot 2019-07-30 at 12 50 57 PM" src="https://user-images.githubusercontent.com/29539247/62108882-c207b880-b2c8-11e9-8776-b8b86b2047b3.png">

**Comment by jalada** [comment]
Hmm looks like you have a problem with your app building. Does `react-native run-android` work for you?

**Comment by roydipti23** [comment]
To build we use the command:

react-native bundle --dev false --platform android --entry-file index.android.js --bundle-output build-android/main.jsbundle --assets-dest build-android

**Comment by roydipti23** [comment]
`react-native run-android` doesnt work

**Comment by roydipti23** [comment]
@jalada ours is a hybrid app, it is not only and only react native; that is why` react-native run-android` doesnt work

**Comment by jalada** [comment]
Hmm OK. Hybrid apps aren't particularly supported by cavy-cli. If your app can't be built and run by the standard `react-native` command line tools, cavy-cli won't work. You may want to [try the native reporter](https://cavy.app/docs/guides/cavy-native-reporter/installing-and-usage)? 

I'm going to close this issue as this isn't an issue with Cavy itself as far as I can tell. But please feel free to continue discussing :)

**Comment by roydipti23** [comment]
HI @jalada, we have tried native reported, but if the test cases are not running only, we cannot expect to get the report right.

**Comment by roydipti23** [comment]
I would recommend trying to integrate cavy with hybrid apps as well, because huge organisational apps would be mostly hybrid, to provide support for native features. Essentially organisations would have differents modules, like for example payments- that would be used same across verticals. 

Running a react native app differently should be supported.

**Comment by AbigailMcP** [comment]
Hi @roydipti23 - realise this might be a little late now, but you can now use Cavy CLI even if you cannot build your app using `react-native run-android` (or `react-native run-ios`).

Build and run your app as you would normally then, with your app running, run Cavy tests with the `--skipbuild` option:

`cavy run-android --skipbuild`

This will start the test server and listen for test results without first trying to build the app using the React Native CLI. Just refresh your app to run the tests.

**Comment by roydipti23** [comment]
@AbigailMcP thanks for the support, but not sure if we can test this right away; since the organisation might have moved out of cavy.
