### ISSUE TITLE
ReferenceError: Can't find variable component on v.2.2.0

### ISSUE THREAD

**Issue by llamaluvr** [pixielabs/cavy#144]
I upgraded to version 2.2.0 yesterday, and got the error "ReferenceError: Can't find variable component" when using an old-style ref with `generateTestHook()`, like:

```
<TextInput
            ref={this.props.generateTestHook('LoginForm.Password', c => {
              this._passwordTextbox = c;
            })}
</TextInput>
```

Seems like `generateTestHook.js:35` might be the culprit, since it's trying to access a `component` variable that isn't one of the function arguments:
```
// Either calls the ref generating function or returns the ref attribute.
  function preservedRef(ref) {
    if (typeof ref == 'function') return ref(component);
    return ref;
  }
```

When I downgraded to 2.1.1, everything was fine, again.

Thanks!

**Comment by jalada** [comment]
Uhoh! Thanks for the report @llamaluvr, I'm getting right on this and we'll release 2.2.1 ASAP.

**Comment by jalada** [comment]
Fixed! https://github.com/pixielabs/cavy/commit/80223054c4e2a37125ea924a57a6abdb9c262094
