### ISSUE TITLE
hook decorator should use hoistNonReactStatics

### ISSUE THREAD

**Issue by gponsinet** [pixielabs/cavy#146]
Hello everyone !

I found a problem in my react-native application when using decorator [hook](https://github.com/pixielabs/cavy/blob/ae28c4e6e16e6a1773fb67875c86461184af2b3d/src/hook.js#L45) on a component.
I use [react-navigation](https://github.com/react-navigation/react-navigation) and static method `navigationOptions`.

While hook doesn't hoist the static methods of wrapped components, all statics methods will be `undefined` when using it as a decorator.

I think hook should follow the react rules for [higher order components](https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over).

Thank you

**Comment by jalada** [comment]
Thx @gponsinet! Sounds like something we missed. We'll update this issue once we've released a new version that addresses this.
