### ISSUE TITLE
missing and incorrect typings

### ISSUE THREAD

**Issue by mptorz** [pixielabs/cavy#149]
1. `wrap` function is not typed at all and I cannot import it without getting errors:
```
Module '"../../../../../../../Users/mptorz/XXXXXX/node_modules/@types/cavy"' has no exported member 'wrap'.ts(2305)
```

2. `findComponent` has incomplete typings
It would be good to change:
`findComponent(identifier: string): Promise<React.Component>`
to
`findComponent<P = {}, S = {}>(identifier: string): Promise<React.Component<P, S>>`

Currently, the type is fixed to always be `React.Component<{}, {}, any>`, which means that whenever I want to use the the component returned by `findComponent` then I cannot access the props or state without causing typescript errors.

After updating it how I suggested, we would be able to pass appropriete typings for example like that:
`const button = await spec.findComponent<IButtonProps, IButtonState>('LoginScreen.Button')`

I would be really grateful if someone submits a PR with the updated types, or if you want I can make a PR myself, but then please assign the ticket to me and reply in the issue @jalada @AbigailMcP

**Comment by mptorz** [comment]
Also it would be good to change:
`findComponent(identifier: string): Promise<React.Component>`
to
`findComponent<P = {}, S = {}>(identifier: string): Promise<React.Component<P, S>>`

Currently, the type is fixed to always be `React.Component<{}, {}, any>`, which means that whenever I want to use the the component returned from `findComponent` then I cannot access the props or state without causing typescript errors.

After the proposed change, we would be able to pass appropriete typings for example like that:
`const button = await spec.findComponent<IButtonProps, IButtonState>('LoginScreen.Button')`

@jalada @AbigailMcP

**Comment by AbigailMcP** [comment]
Hi @mptorz, apologies for the late reply, we've been a little busy here at Pixie Labs.

Thanks for raising this issue, I'm very happy for you to submit a PR to Definitely Typed for the updated types for `findComponent` and the new types for `wrap`.

**Comment by mptorz** [comment]
Cool, thanks :)

**Comment by AbigailMcP** [comment]
Hi @mptorz ! I've submitted a PR to Definitely Typed for the wrap types, so hopefully that should be in soon.

Re the `findComponent` typing,  if we change it to your suggestion we get the linting error 'No unnecessary generics'.

Check out the last example on: https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md

Bearing this in mind and keeping the type definition as it is, you should be able to fix your code with a type assertion. Something like:

```js
interface FCProps {
  text: string;
}
const FunctionComponent: React.FunctionComponent<FCProps> = ({ text })  => {
  return <Text>{text}</Text>;
};
const WrappedFunctionComponent = wrap(FunctionComponent);
```

```js
// In your test:
const functionComponent = await spec.findComponent('WrappedFunctionComponent') as React.Component<FCProps>;
// Now I can access the props of the wrapped component:
if (functionComponent.props.text !== 'text') {
  throw new Error();
}
```

**Comment by mptorz** [comment]
Okay, I understand. Just out of curiosity do you know why 
this is bad :
```
function parse<T>(): T;
const x = parse<number>();
```
And this is good:
```
function parse(): {};
const x = parse() as number;
```

I have always thought that it is the other way around and I have never seen this rule. If you happen to know why this is a rule then that would be helpful for me, because I am just curious and I couldn't find any good explanations.
