### ISSUE TITLE
No export for the 'wrap' member in the @types

### ISSUE THREAD

**Issue by simondobson** [pixielabs/cavy#154]
I'm testing out cavy with a typescript project and I'm getting the following error

```
...react-native/node_modules/@types/cavy"' has no exported member 'wrap'.
```

while trying to use the `wrap` on ReactNative's TextInput as described in the docs below

https://cavy.app/docs/api/test-hooks

Checking in the repository found in the README I didn't see an export named `wrap` in the definition

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cavy/index.d.ts

**Comment by AbigailMcP** [comment]
Thanks for raising @simondobson ! We're tracking this issue here https://github.com/pixielabs/cavy/issues/149 and I believe that @mptorz was going to be working on a PR.

@mptorz - let me know if you don't have time to do this anymore and I'll happily pick it up 👌

**Comment by mptorz** [comment]
@AbigailMcP I am really sorry that I disappeared without saying. I was very keen to contribute, but a lot of stuff came out suddenly and yea, I actually don't have much time and I don't have my laptop with me. Again really sorry :(

**Comment by AbigailMcP** [comment]
Oh no worries at all @mptorz! I'll get on it :)

**Comment by AbigailMcP** [comment]
Hi @simondobson - I'm currently waiting for DefinitelyTyped to approve my PR for the new wrap typings. Hopefully should be in soon!

**Comment by AbigailMcP** [comment]
New types for wrap were published at the beginning of this week 👌
