### ISSUE TITLE
NativeBase form components can't be found

### ISSUE THREAD

**Issue by Poeticode** [pixielabs/cavy#156]
I was writing up a test for a form today, and I noticed that all of my `spec.findComponent("SomeFormInput");`'s would fail. They could be found once I took them out of NativeBase's Form component.

Have you guys used NativeBase with Cavy before, or know of any tips to get it to work? I believe NativeBase wraps the native components, so I'm imagining that's what's causing this issue.

**How To Replicate:**

The component:
```js
import { Form, Item, Label, Input } from 'native-base';
import { hook } from 'cavy';

class AuthScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      someValue: '',
    };
  }

  render() {
    return (
      <Form>
        <Item>
          <Label>Some Input</Label>
          <Input
            ref={this.props.generateTestHook('NativeBaseTextInput')}
            onChangeText={(someValue) => this.setState({ someValue })}
          />
        </Item>
      </Form>
    );
  }
}
export default hook(AuthScreen);
```

The spec:
```js
export default function(spec) {

  spec.describe('Logging in', function() {

    spec.it('works', async function() {
      await spec.findComponent('NativeBaseTextInput');
      // findComponent times out. Can't use exists or fillIn, either.
    }
  }
}
```

**Comment by AbigailMcP** [comment]
Hey @Poeticode ! Sorry it took me so long to respond to this - it slipped off my to do list 😞 

Did you get this to work in the end?

I just copy pasted and ran your code and the test passed... I can't see anything wrong with it! I can use `exists` and `fillIn` too with no problem.

- cavy: 3.1.0
- native-base: 2.13.8
- react: 16.8.3
- react-native: 0.59.9

**Comment by Poeticode** [comment]
D'oh! I didn't think it would matter much, but I forgot to add the `floatingLabel` attribute to the <Item>'s in the example code. Lo and behold, that was the source of our issue. 

https://docs.nativebase.io/Components.html#floating-label-headref

I believe it's due to floatingLabel creating its own Input field under the hood, of which you can't set its ref, and so Cavy can't find it. I believe this issue can safely be closed, unless you have any ideas on how to work around this.

**Comment by AbigailMcP** [comment]
Ahhh I see! I'm going to close this issue, but reopen a new one that tracks the issue with Native Base's `floatingLabel` specifically. Thanks!
