### ISSUE TITLE
Support automation

### ISSUE THREAD

**Issue by joaomilho** [pixielabs/cavy#16]
Just tried cavy today and it looks cool. One thing that I would like to understand is how do you plan to automate it, meaning, run a console command and get 0/1 result. Any insight appreciated.

**Comment by TGPSKI** [comment]
https://github.com/pixielabs/cavy/pull/20 addresses most of this - you will need to integrate your build flow with a CI server to really take advantage of automated testing with Cavy.

**Comment by pietropizzi** [comment]
Since #20 is now split up in multiple PRs, but none of them address CI compatibility, is that still coming?

**Comment by TGPSKI** [comment]
Yep! I just wanted to break out the changes into smaller PR's. You can still clone https://github.com/TGPSKI/cavy/tree/add-jenkins-reporting while I am staging the changes over a few PRs.

**Comment by curioustechizen** [comment]
Could you elaborate on the `If test === pass` part? Does it mean the the CI server has to inspect the result.{json|xml} file to figure out whether the test passed?

**Comment by CoreyAR** [comment]
What is the status on this feature? I checked out the `add-jenkins-reporting` branch and saw that it is using this commit `446bbcfd1ee843d4e6aa3fb1fc207c53e7fe0ec7` but when I run the app I no reporting files are being generated.

**Comment by jalada** [comment]
Hi @CoreyAR! Automation is still on the roadmap, but development hasn't started yet.

Here's what we propose (Context: https://github.com/pixielabs/cavy/pull/21#issuecomment-304357021)

 - When Cavy runs, it should generate some kind of test report object.
 - Construct an adapter API for using these objects that would allow them to be passed to other services. This could be used by community-created packages. Imagine `cavy-jenkins` and `cavy-circle-ci` packages.
 - Provide a sample adapter that writes to a file.

You are welcome to help out with this via input or code! It's also something that we have planned to start work on ourselves, but there's no definite timeline right now.

**Comment by jalada** [comment]
We've released a new version of Cavy (0.5.0) that adds support for [cavy-cli](https://github.com/pixielabs/cavy-cli). **cavy-cli** can be used to automate running Cavy tests. Check out the README for the CLI for more info :)
