### ISSUE TITLE
Tests seem to run twice

### ISSUE THREAD

**Issue by cwilby** [pixielabs/cavy#163]
Recently setup cavy-cli tests - everything is working awesome. (seriously, thanks to the team for building this product it's incredible).

But!  The tests seem to run twice on `cavy run-ios`.  Once when the app is building without test results, then again when the app has finished building with test results. Is this a common pitfall I've fallen into?

**Comment by AbigailMcP** [comment]
Hey @cwilby - this is really strange! And not a scenario I've come across before using Cavy. Can you give some more details / code snippets to show the way Cavy is configured in your application?

**Comment by jalada** [comment]
Closing for now but please do share more details if you have them and we'll see if we can help.

**Comment by cwilby** [comment]
Oops! Absolutely meant to come back to this, apologies.

I will reproduce today and take some screen captures. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cwilby** [comment]
Just got back to this.  Here's what I'm experiencing if it helps.

![Kapture 2020-03-24 at 16 23 44](https://user-images.githubusercontent.com/13686317/77486021-e8480e80-6deb-11ea-902d-0110fcd5b0d2.gif)

**Comment by pqkluan** [comment]
For anyone stumble upon this problem.

This issue only happen if you already have running metro bundler AND Fast Refresh enabled.
So the solution is either kill the bundler before running test or manually disable Fast Refresh via dev menu.
