### ISSUE TITLE
Production App

### ISSUE THREAD

**Issue by shiftrtech** [pixielabs/cavy#165]
Hi guys i want to try Cavy on my app.

I want to know how do Cavy difference from testing and production.

Aditionally, i want to know if the cons abouts cavy published here, were resolved: 

[Cons](https://medium.com/@roydipti23/decoupling-cavy-react-native-integration-testing-5e89efb06daa) .

I can't see on your code how `wrap`, `generateTestHook` or `hook` takes into account the 
current environment or how to optimize bundle size, can you please explain me about this.

Thanks.

**Comment by jalada** [comment]
Thanks @shiftrtech. Some of the issues in the blog post you linked to have been resolved in newer versions of Cavy, for example we now have a `useCavy` hook that allows you to use it with function components. Take a look through [the Cavy website](https://cavy.app/) for more info.

Regarding testing & production: For the time being, fully and completely decoupling Cavy out of your codebase is not something Cavy inherently supports. Our priorities have always been:

1. Quick set up
2. Pure JS
3. Cross-platform

and we have yet to find a solution that satisfies these. Appreciate this isn't perfect, and we're always open to suggestions on how to improve this! For now, we believe it's an acceptable trade-off.

I'm closing this issue for now, but please do reply if you have any thoughts & happy to continue to discuss.
