### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by devdelpiero** [pixielabs/cavy#173]
Compared to wix detox, I feel cavys documentation is lacking a bit. Would be nice to have more test scenario examples, as well as a CI integration example. Roadmap for upcoming features would be nice. Was orignally told to post on the cavy app repository. Its been a week and no feedback!

**Comment by AbigailMcP** [comment]
@devdelpiero please refrain from re-opening closed issues. See my response in your open issue https://github.com/pixielabs/cavy-app/issues/9.
