### ISSUE TITLE
Support stateless components without a wrapping function

### ISSUE THREAD

**Issue by faceyspacey** [pixielabs/cavy#18]
Basically everything has trended towards stateless functional components, using *Recompose* etc. Nobody wants to use class components anymore. And cluttering your codebase with additional wrappers also is far from ideal. 

I feel like there should be a lower level and more automated connection to component instances based on a simple `id` prop you supply them. What about ways to monkey patch into the internals of React and make something like that happen??

**Comment by AbigailMcP** [comment]
Yep you're totally right, @faceyspacey. We'd love for Cavy to be better compatible with stateless functional components too and would be more than happy to see its reliance on `ref`s replaced with something better suited to the task...

What that looks like specifically, we're not 100% sure yet. Very happy to hear suggestions/discuss possible alternatives.

**Comment by TGPSKI** [comment]
https://github.com/pixielabs/cavy/pull/20 shows an example to wrap stateless functional components.

Here's the conditional test wrapper:
https://github.com/TGPSKI/cavy/blob/add-jenkins-reporting/sample-app/EmployeeDirectory/app/helpers/cavy.js

And here's how to define refs for stateless functional components for both tests enabled and tests disabled:
https://github.com/TGPSKI/cavy/blob/add-jenkins-reporting/sample-app/EmployeeDirectory/app/EmployeeListItem.js#L7

**Comment by talarari** [comment]
a nice solution would be to write a babel transform plugin to auto-wrap all functional components only in dev mode only.
something like     
```
.bablerc
{
  "env": {
    "development": {
      "plugins": ["transform-cavy"]
    }
  }
}
```
also, instead of using genereateTestHook everywhere, you could just use a testID prop (like this https://facebook.github.io/react-native/docs/view.html#testid)
and generate the ref. if there's already a ref set, just wrap it.

that way, the changes to the application code would be very minimal.

**Comment by talarari** [comment]
thought about it some more and a babel plugin is a little overkill.
i guess most of the time you would set the ref on a react-native base component like view,text,touchable anyway.
so you probably wouldn't have to wrap that many functional components.

**Comment by jalada** [comment]
You'll still need a wrapping function, but #121 (using React Hooks to accomplish the functionality of `wrap()`) will at least reduce the depth of your component heirarchy.
