### ISSUE TITLE
Can't scroll with Cavy

### ISSUE THREAD

**Issue by JB-CHAUVIN** [pixielabs/cavy#185]
Hello, 

I don't see in the API any way to scroll to the bottom of a scroll view.

Is there any way to do this ?

Regards

**Comment by AbigailMcP** [comment]
Hi there! You're right, there's no in-built API to scroll a `<ScrollView>` - but what exactly are you trying to test here?

Cavy should be able to interact with all the elements inside your `<ScrollView>` regardless of the position of the scroll. 

Are you testing that something happens programmatically when the user scrolls to the bottom?

If you need to scroll to the end for your test you could achieve this using Cavy's [`findComponent()` helper](https://cavy.app/docs/api/test-helpers#findcomponentidentifier), which resolves to the component itself, and React Native's [`scrollToEnd()` method](https://reactnative.dev/docs/scrollview#scrolltoend):

```js
spec.describe('My feature', () =>
    spec.it('scrolls and does something', async () => {
      const scrollView = await spec.findComponent('myScrollView')
      scrollView.scrollToEnd();
    })
  );
```

Let me know if this helps!
