### ISSUE TITLE
Proper way about implementing Cavy into React Native in TypeScript Ecosystem. 

### ISSUE THREAD

**Issue by robto09** [pixielabs/cavy#189]
Hellow!

I would like to know is there are some snipped or project example to be able to see how to implement Cavy there. In special with TypeScript  Screens with class components in this format.

```
type Props = {
  navigation: NavigationStackProp;
};

type State = {
  variable: string;
};

class ExampleScreen extends React.PureComponent<Props, State> {
...

export default connect(null, mapDispatchToProps)(ExampleScreen);
```

Thanks

**Comment by JonathanAndrews** [comment]
Hi Robert,

We don't have any example code snippets but you can find all the types defined here.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cavy/index.d.ts

If you wanted to call `this.props.generateTestHook('Scene.TextInput')` in a component, you would need to define  `generateTestHook`'s type in the Props type.

```ts
type Props = {
  generateTestHook: TestHookGenerator;
};
```

I've added a ticket to our backlog to improve Typescript documentation.

Let me know if this helps.

**Comment by robto09** [comment]
Thank you very much for the support Jonathan! 

Yes, the Props definition its ok.
After that I do destructuring.
 ```
 render() {
    const { generateTestHook } = this.props;
  return (
```

And  in the View which is the one I want to ref. Like this:   
```
<View ref={generateTestHook('Scene.Welcome')}
```

And in the component something like this:

```
const TestableScene = hook(ExampleScreen);
export default connect(null, mapDispatchToProps)(TestableScene);
```

But then I run the cavy run-ios , app starts well but appears this warning. So test are not done.

1) Logging in: works  ❌
   Could not find component with identifier Scene.Welcome

Any idea?

**Comment by JonathanAndrews** [comment]
Hi Robert,

Sorry for the slow response, we are quite busy at the moment at PixieLabs.
I am not sure what the problem is.

Is the View component that you are trying to test visible if you boot the app normally?
And could you post your the test code here so I can see how it's written?

A final thing you could do to get more information on what is going wrong is to `console.log` the test hook store before passing it into the Tester component, see below. Then by running a single test that visits the target view, you should be able to see the registered hooks printed in the browser console.
```js
import React, { Component } from 'react';
import {AppRegistry} from 'react-native';
import {name as appName} from './app.json';

import { Tester, TestHookStore } from 'cavy';

import EmployeeDirectoryApp from './app/EmployeeDirectoryApp';

import EmployeeListSpec from './specs/EmployeeListSpec';

const testHookStore = new TestHookStore();

class AppWrapper extends Component {
  render() {
    console.log(testHookStore)
    return (
      <Tester specs={[EmployeeListSpec]} store={testHookStore} waitTime={1000}
        startDelay={3000}>
        <EmployeeDirectoryApp />
      </Tester>
    );
  }
}

AppRegistry.registerComponent(appName, () => AppWrapper);

```

**Comment by robto09** [comment]
No problem! 
Yes the view is visible when I boot the app.
I did the console.log things but did not show me something of interest.
About the test, just wanted to know if the element was present. So its very simple.

```
export default function(spec) {
  spec.describe('Logging in', function() {
    spec.it('works', async function() {
      await spec.exists('Scene.TextInput');
    });
  });
}```

This is an screen which is connected to redux. Is this way the right one to do it? About cavy way.

```
const TestableScene = hook(ExampleScreen);
export default connect(null, mapDispatchToProps)(TestableScene);
```

**Comment by JonathanAndrews** [comment]
Hi Robert, 

So far I have been unable to recreate your error.

It would be much easier for us to see what is going wrong if you were able to provide a sample app that has the failing test.
If you aren't able to, I am going to setup a redux react native app but finding the problem might take some time.

Thanks

**Comment by robto09** [comment]
> Hi Robert,
> 
> So far I have been unable to recreate your error.
> 
> It would be much easier for us to see what is going wrong if you were able to provide a sample app that has the failing test.
> If you aren't able to, I am going to setup a redux react native app but finding the problem might take some time.
> 
> Thanks

Thank you very much for your help. I have been busy now, havent have time to do a test app with redux to see if happen in other environment.
