### ISSUE TITLE
Call methods from wrapped Cavy components (multiple refs ?)

### ISSUE THREAD

**Issue by JB-CHAUVIN** [pixielabs/cavy#190]
Hello,

I wrapped my TextInput like in the doc :
```
import { View, TextInput } from 'react-native';
import { useCavy } from 'cavy';

export default () => {
  const generateTestHook = useCavy();

  return (
    <View>
      <TextInput
        ref={generateTestHook('Scene.TextInput')}
        onChangeText={...}
      />
    </View>   
  )
};
```

I would like to access methods from my TextInput component (calling .focus() method from the TextInput component as an example).

But my TextInput's ref already have a ref. How can I add multiple ref to my components, and have it wrapped by Cavy and register the ref in the JS.

**What I would like to do is to call the .focus() method of my TextInput :-)**

Best regards

**Comment by AbigailMcP** [comment]
Hi there! If you'd like to generate a Cavy test hook for a component that already has another ref, you can pass the non-Cavy ref in as the second argument to `generateTestHook`.

e.g.

```jsx
<TextInput
  ref={generateTestHook('Scene.TextInput', this.myRef)}
  onChangeText={...}
/>
```

Let me know if this is what you were after!

(relevant docs: https://cavy.app/docs/api/test-hooks#generatetesthookidentifier-ref)

**Comment by AbigailMcP** [comment]
Hi @JB-CHAUVIN ! Looks like there's actually a bug when you're using object refs generated via `useRef` together with Cavy's `generateTestHook()`.

We're working on a fix in this PR: https://github.com/pixielabs/cavy/pull/198

I'll let you know when it's in - maybe this will fix whatever issues you were previously having!

**Comment by AbigailMcP** [comment]
Bug fix for using your own refs now in the most recent release :) - closing this issue! shout if this doesn't fix your issue @JB-CHAUVIN !
