### ISSUE TITLE
Passing an object ref as second argument to generateTestHook doesn't work

### ISSUE THREAD

**Issue by MrLoh** [pixielabs/cavy#197]
If you need an ref for other reasons than cavy and created that ref as `cont myRef= useRef()` and than call `generateTestHook('MyIdentifier, ref)` it doesn't work. 

Looking at the code it becomes clear why, in line 31 you return the ref from the ref function that `generateTestHook` returns if it is not a function, that will of course do nothing, as the ref prop is of type `RefCallback<T> | RefObject<T>` the `generateTestHook` call always returns a function so it always runs into the case `RefCallback<T>` and that is defined as `(instance: T) => void` so whatever that function returns is irrelevant.

https://github.com/pixielabs/cavy/blob/5c54a9de5cceedd709c7d4e9afb03709db820701/src/generateTestHook.js#L16-L33

Line 31 should be changed to
```js
if (typeof ref == 'function') {
  ref(component);
} else {
  if (ref && ref.current) {
    ref.current = component;
  }
}
```

I would be happy to file a PR

**Comment by jalada** [comment]
Thanks @MrLoh! We're fully stacked at Pixie Labs right now, but when we've got some downtime we'll take a look at this & your PR and make some progress.

**Comment by MrLoh** [comment]
@jalada it's really a quite simple change, let me know if I can do anything to move this along, after all it is a bug in the public API.

**Comment by AbigailMcP** [comment]
Fixed in https://github.com/pixielabs/cavy/pull/198 (version 4.0.1)

**Comment by MrLoh** [comment]
@AbigailMcP Thanks for moving this along so quickly.
