### ISSUE TITLE
Add the possibility to start a test from a deepLink

### ISSUE THREAD

**Issue by clind-arthur** [pixielabs/cavy#206]
Hello, It will be very useful to add the possibility to start a test from a deepLink. 
For now, because the index in replace by index.test.ts when we start the cavy test, the hot javascript reload not allow to do this.
I 've just started to use cavy E2e tests, so I I have no proposals for the moment.

**Comment by jalada** [comment]
Hmm...app links are handled in part by the native layer, which makes it tricky for Cavy to influence. Could you mock out [`Linking.getInitialURL()`](https://reactnative.dev/docs/linking#getinitialurl) to trigger the required app state?

**Comment by Pierre-CLIND** [comment]
Thanks @jalada 

We can mock a function using Cavy, like we do with jest for example?

**Comment by jalada** [comment]
Hmm...Cavy doesn't have built-in support for mocks but you should be able to load in jest or some other mocking library in your tests. It's not something I've tried specifically.

Alternatively, you could give your tests a way to simulate a deep link, e.g. by having a function on your app component that you can call from within your tests to simulate the effect of a deep link.

**Comment by jalada** [comment]
Closing; we're unlikely to support deep links given that it's part of the native layer. Open to any ideas of neat ways of doing this, though!
