### ISSUE TITLE
React Navigation doesn't unmount previous screens, causes `spec.findComponent` to return true.

### ISSUE THREAD

**Issue by Zooheck** [pixielabs/cavy#209]
Hello Pixielabs team and fellow Cavy users!

I have discovered an issue while using Cavy & [React Navigation](https://reactnavigation.org/), specifically Cavy registering a component as "existing," even though the given component is not present on the screen. React Navigation preserves its navigation history by not unmounting previously visited screens, and instead preserving the previously visited screens in the JSX tree while keeping them invisible to the user. Because of this implementation, spec.findComponent will always succeed even if the screen w/ the component in question is not at all visible to the user.

I discovered this behavior when I was testing an app's back button functionality. My test essentially navigated through a specific path of the app and kept track of the ID of each screen I visited. After reaching the end of the navigation path, the test pressed the back button, attempting to confirm that the screen ID's appeared in the reverse order that they were visited. Because of the React Navigation behavior that I described above, my test suite was yielding false positives, even though when manually using the app, the back button functionality was not working properly.

Just wanted to see if anyone else had encountered this problem and reached an effective solution. Let me know if anything I wrote was unclear, and I'll be happy to clarify!

**Comment by jalada** [comment]
Hi @Zooheck. Hmm, that's some frustrating behaviour from React Navigation for the purposes of Cavy. Doesn't that also mean that elements mounted on previous screens continue to 'live'? e.g. if they're animating, or have timers set of some kind? That feels like that would cause a whole bunch of issues, not just Cavy ones.

I'll leave this issue open in case anyone has any suggestions. If we get chance, we'll take a look at Cavy & React Navigation ourselves.

**Comment by jalada** [comment]
We're using React Navigation for both [cavy-tester](https://github.com/pixielabs/cavy-tester) and [cavy-sample-app](https://github.com/pixielabs/cavy-sample-app) with no issues, though I appreciate we're not doing exactly the same test as you. I'm going to close this, as it's not something we're about to tackle, but if anyone also has this problem & has found a solution, please share!
