### ISSUE TITLE
Can't close modals of react-native-modal-datetime-picker package

### ISSUE THREAD

**Issue by BParvatkar** [pixielabs/cavy#213]
I am using the react-native-modal-datetime-picker package to choose time on the app screen. I am able to press the onCancel and onConfirm options using spec helpers, they are even executed properly and sets the isShowTime to false, but the modal still remains on the screen. I created modal using react-native-modal package to verify if my spec helpers work on normal Modal and they did work. Seems that the issue is only with the modal created using react-native-modal-datetime-picker package.

The code is as follows:
```
//App.js
import DateTimePicker from 'react-native-modal-datetime-picker';
import { useCavy, wrap } from 'cavy';

const generateTestHook = useCavy();
const TestDateTimePicker = wrap(DateTimePicker);

const [isShowTime, setIsShowTime] = useState(false)
const showTime = () => { setIsShowTime(true) }
const hideTime = () => { setIsShowTime(false) }
const setDate = () => {//some process}

<TestTouchableOpacity onPress={showTime}
  ref={generateTestHook(TestConstants.constants.TouchableDateTimePicker)} 
>
.....// some components here
</TestTouchableOpacity>
<TestDateTimePicker
    ref={generateTestHook(TestConstants.constants.TimePicker)}
    isVisible={isShowTime}
    mode={"time"}
    textColor={color.blue}
    onCancel={hideTime}
    onConfirm={setDate}
/>

// Specs
await spec.exists(TestConstants.constants.TouchableDateTimePicker);
await spec.press(TestConstants.constants.TouchableDateTimePicker);
await spec.pause(1000)
const TimePicker = await spec.findComponent(TestConstants.constants.TimePicker);
TimePicker.props.onCancel();
```

**Comment by jalada** [comment]
Looks like [react-native-modal-datetime-picker](https://www.npmjs.com/package/react-native-modal-datetime-picker) is a wrapper around native datetime pickers. Cavy lives in JS-land only so can't do anything to interact with native components. For now, we have no plans to add native hooks to deal with this. You have a couple of choices:

1. Skip opening the modal; essentially 'stub' it and just trigger the callback functions somehow.
2. Swap to a native testing tool like XCTest.

Sorry we can't be more helpful!
