### ISSUE TITLE
Update Peer Deps to support React 17+

### ISSUE THREAD

**Issue by alexburkowskypolysign** [pixielabs/cavy#226]
please update the peer dependencies in the package.json to support react 17 and later versions of react native.

suggested fix location: https://github.com/pixielabs/cavy/blob/5c1404f61959a1c52b7aa4fbcff2e03d555e3081/package.json#L25

```json
  "peerDependencies": {
    "react-native": "^0.65.1",
    "react": "^16.8.3 || ^17.0.0"
  },
```

**Comment by jalada** [comment]
Fixed in #229
