### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by llaine** [pixielabs/cavy#24]
I'm trying to integrate this with my app (which is using redux), how can I manage to makes my component works? 
I see that you guys are using `context` in the `constructor` of the hook method. 
I guess this is messing with my redux provider.
Any ideas to make it works?

**Comment by geecurve** [comment]
Have the same issue with redux and cavy not playing nicely.

**Comment by jalada** [comment]
Thanks both, we'll look into this :)

**Comment by trcm** [comment]
I was able to hook Cavy up while using redux by wrapping the Tester component with the Provider for the redux store.  
```
class App extends Component {
  render() {
      return (
	<Provider store={store}>
	     <Tester specs={[AppSpec]} store={specStore} waitTime={4000}>
		  <TestApp />
	    </Tester>
	</Provider>
    );
  }
}
```

**Comment by jalada** [comment]
Sounds like Redux + Cavy = ❤ ? 😎

@llaine does @trcm's suggestion work for you?

**Comment by llaine** [comment]
@jalada Indeed it works using this.

**Comment by adimittal** [comment]
This is giving me "could not find "store" in the context of "Connect(Hook(mycomponent))".  either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Hook(mycomponent)) in connect options.

**Comment by AbigailMcP** [comment]
Hey @adimittal !

I can't seem to replicate this issue... I've set up a quick app which uses Redux and I'm able to use the set up you've described:

```js
//...

const store = createStore(testReducer);
const testHookStore = new TestHookStore();

class AppWrapper extends Component {
  render() {
    return (
      <Provider store = {store}>
        <Tester specs={[spec]} store={testHookStore}>
          <App />
        </Tester>
      </Provider>
    );
  }
}

//...
```

I can then use both Cavy and Redux in an inner component:

```js
export default hook(connect(mapStateToProps, mapDispatchToProps)(Component));
```

- cavy: 3.1.0
- react: 16.8.3
- react-native: 0.59.9
- react-redux: 7.1.3
- redux: 4.0.4
