### ISSUE TITLE
Question: Integration testing of (non-UI) RN modules

### ISSUE THREAD

**Issue by curioustechizen** [pixielabs/cavy#26]
Thanks for Cavy! It is great for integration testing RN Components.

Are there any tips for how to test non-UI modules. What I really want to do is call a method on my RN module and assert the return value. I want to run the tests on real devices because that way I exercise the native Android/iOS code too. 

Currently, I can create a wrapper component but it might not scale.

**Comment by jalada** [comment]
Hi @curioustechizen, that sounds like something that belongs in unit tests. Is your issue that you want to run unit tests on a real device?

Closing because this isn't something for Cavy, but I'm happy to continue the discussion :+1:

**Comment by curioustechizen** [comment]
We have an RN module that does not have a UI. It abstracts platform-specific functionality and provides a uniform API for RN. An example I can think of is a FileManager module.

Now, we do have unit tests on the respective platforms (Android and iOS). But I believe it makes sense to also test this at the RN layer. So, for example, I'd like to use the FileManager JS API to write something to a file, then read from the file and assert that what I read is indeed what I wrote. Crucially, this has to run on the real device.

Currently, I do this by using a UI component that sets the output of the RN API to a TextView on screen (for example, read the contents of the file and set it as the text to a TextView). I can then use Cavy/Appium to get the text from the TextView and do an assertion.

This works but seems a little circuitous. You shouldn't really need a UI field to test this. This is the direction I'm exploring: if it is possible to test RN code that runs on real devices without needing a UI.

Does any of that make sense? 😃
