### ISSUE TITLE
No response from Cavy 

### ISSUE THREAD

**Issue by juliscotto** [pixielabs/cavy#286]
Please help, I'm trying to run `cavy run-ios --simulator="iPhone 11" --verbose` but I'm getting 

success Successfully launched the app on the simulator
cavy: react-native exited with code 0.
cavy: Listening on port 8082 for test results...
No response from Cavy within 2 minutes.
Terminating processes.

config:

```
import React, { Component } from "react";
import { AppRegistry } from "react-native";
import { Tester, TestHookStore } from "cavy";
import ExampleSpec from "./specs/exampleSpec";
import LoginScreen from "./src/screens/LoginScreen/LoginScreen";

const testHookStore = new TestHookStore();

class AppWrapper extends Component {
  render() {
    return (
      <Tester specs={[ExampleSpec]} store={testHookStore} waitTime={300000}>
        <LoginScreen />
      </Tester>
    );
  }
}


AppRegistry.registerComponent("PYO", () => AppWrapper);
```

Please I would appreciate some help. Heres my package.json:
"devDependencies": {
    "@babel/core": "^7.8.6",
    "@testing-library/react-native": "^9.1.0",
    "babel-jest": "~25.2.6",
    "babel-preset-expo": "~8.1.0",
    "cavy": "^4.0.2",
    "detox": "^19.6.9",
    "enzyme-adapter-react-16": "^1.15.6",
    "jest": "26.6.3",
    "jest-node-exports-resolver": "^1.1.6",
    "react-test-renderer": "17",
    "ts-jest": "26.5.5"
  },
  "jest": {
    "preset": "react-native"
  },
...
 "react-native": "~0.62.2",

**Comment by jalada** [comment]
Hey @juliscotto, can you see the app booting in the simulator? Does your ExampleSpec run?

**Comment by juliscotto** [comment]
I needed to add `registerRootComponent(AppWrapper);`  instead of `AppRegistry.registerComponent("PYO", () => AppWrapper);`. 

Sorry! and thanks!
