### ISSUE TITLE
Uses different hooks method for fillIn

### ISSUE THREAD

**Issue by llaine** [pixielabs/cavy#29]
Hello, this issue is more a question:
Is there a way to override the [`fillIn`](https://github.com/pixielabs/cavy/blob/master/src/TestScope.js#L140) and `press` method with other function on the component? 

Something like : 

```ts
  async fillIn(identifier, str, fn: Function) {
    const component =  await this.findComponent(identifier);
    component.props[fn](str);
  }
```

I'm already overriding theses function in my component which makes `cavy` unusable with my codebase. 
If I could have a way to pass the function to trigger the fillIn would be nice.

**Comment by jalada** [comment]
Hi @llaine, you can write your own spec helper functions in a similar style to `fillIn` (making use of `findComponent`) to call whatever function you like, and then use those within your specs.

**Comment by llaine** [comment]
Hello @jalada thanks for answering, any documentation example on that ?

**Comment by jalada** [comment]
@llaine Not right now. That's a good suggestion though :) I've added an issue #33 to track that.

**Comment by llaine** [comment]
@jalada okay thanks, maybe you could give me some hints about the way to do it, I'm keen to document it if I can.
