### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by matzewagner** [pixielabs/cavy#30]
I'm getting the following error when wrapping a react-native <Button/> into a stateful component with cavy:

'Cannot call a class as a function'

```javascript
import { hook, wrap } from 'cavy'
import { Button, TouchableOpacity, View } from 'react-native'

...
const WrappedComponent = wrap(Button)

...
    return (
	<WrappedComponent
		title='theTitle'
		onPress={() => {}}
		ref={this.props.generateTestHook('theButton')}
	/>
    )
```

Any thoughts on how to resolve this?

**Comment by jalada** [comment]
Hmm, that's odd. What version of React Native are you using?

**Comment by siddarthpatel** [comment]
hey @matzewagner I ran into the same issue. I realized that in my functional component that I was trying to wrap, I exported it in the end in the form of a hook. I changed it back to being a normal export and things worked fine. In your case I would suggest taking a look the way you export your functional component you want to wrap

**Comment by jalada** [comment]
@matzewagner does that help? If so, please close this issue :)
