### ISSUE TITLE
How do I prevent Cavy from resetting?

### ISSUE THREAD

**Issue by siddarthpatel** [pixielabs/cavy#37]

**Comment by jalada** [comment]
Hi @siddarthpatel. It's not possible to prevent Cavy from resetting between test cases. We recommend writing helper functions to perform the same behaviour multiple times for different test cases. If we introduced this functionality, it would constrain other features we'd like to include such as random test order running.

**Comment by LucasBassetti** [comment]
Hi @jalada, 

Is it possible add a prop [here](https://github.com/pixielabs/cavy/blob/3db460ec16d0540bd810159a050eb9c9f35e8357/src/Tester.js#L81) to prevent re-render?

Some like:

```
reRender() {
    if (!this.props.preventReRender) {
      this.setState({key: Math.random()});
    }
}
```

Thanks for this amazing framework!
