### ISSUE TITLE
Testing Native + RN App

### ISSUE THREAD

**Issue by qakapil** [pixielabs/cavy#38]
Hi, I saw Cavy's demo and am really interested in using it for our E2E tests. I have a couple of questions though - 

1. We are in process of migrating our iOS App from native (objective-c) to React Native. As of now around 20% of the features/screens have been migrated to RN. Can I use Cavy to test those 20% RN  part of the app ? Or Cavy can only be used for apps which are fully developed in RN ?

2. Can Cavy run tests on real iOS/Android devices ?

**Comment by jalada** [comment]
Hi @qakapil, thanks for getting in touch.

1. We've not done this, so can't say for sure.
2. Absolutely! It's just JavaScript, so it'll run anywhere your app does.
