### ISSUE TITLE
Add support for ReactNative-web

### ISSUE THREAD

**Issue by piranna** [pixielabs/cavy#39]
Could it be possible to add support for [ReactNative-web](https://github.com/necolas/react-native-web) and test web applications the same way as mobile ones?

**Comment by jalada** [comment]
Hi @piranna. Is there any reason Cavy wouldn't work with react-native-web already? Have you tried it?

**Comment by piranna** [comment]
No, I didn't test it, but since it's running in the Android and iOS emulators, I'm not sure if it has some low level requeriments that would make it impossible to use it with ReactNative-web...

**Comment by jalada** [comment]
@piranna we don't do anything on the native layer, so it should be OK, give it a try!
