### ISSUE TITLE
Add Support for React-Native-Router-Flux

### ISSUE THREAD

**Issue by Aminoid** [pixielabs/cavy#40]
Is it possible to add support for [React Native Router Flux](https://github.com/aksonov/react-native-router-flux)? Right now if I try to hook Cavy with React Native Router Flux, it gives a blank screen and breaks very simple test cases.

**Comment by jalada** [comment]
Thanks @Aminoid. As per discussion via email, please can you provide a sample application that demonstrates the issue? We've not got any experience with that library, so it's going to be simplest if you set it up demonstrating the error and we can take a look from there.

**Comment by Aminoid** [comment]
@jalada I was able to make it work with the router by removing one layer of nesting which was preventing cavy from accessing that screen. It works like a charm and we will be using it for our integration tests. Thanks a lot for your support.

**Comment by jalada** [comment]
Nice! Thanks @Aminoid, glad you got it sorted :) if you have any other questions let me know.
