### ISSUE TITLE
Does not work with React Native 0.46+

### ISSUE THREAD

**Issue by mo-solnet** [pixielabs/cavy#45]
`PropTypes` need to be imported from `'prop-types'` as they are removed from the main `react` library since [RN 0.46+ was released](https://github.com/facebook/react-native/releases/tag/v0.46.4).

**Comment by jalada** [comment]
Thanks @mo-solnet, good catch!

**Comment by meow0703** [comment]
4 days passed guy ! please keep up with latest RN release
Thanks

**Comment by mo-solnet** [comment]
I've already opened a PR to fix this > https://github.com/pixielabs/cavy/pull/47

**Comment by jalada** [comment]
We've got some time scheduled to work on the next release of Cavy this week, and it'll include this fix. Thanks for your patience 🙌
