### ISSUE TITLE
Support before and after test case/suite hooks (e.g. before each, before all, after each, after all)

### ISSUE THREAD

**Issue by stereodenis** [pixielabs/cavy#52]
Popular test frameworks has ability to use before and after callbacks in describe sections. Why there are no such callbacks and is it in roadmap?

**Comment by jalada** [comment]
Can you provide more details of your issue @stereodenis?

**Comment by stereodenis** [comment]
@jalada done!

**Comment by jalada** [comment]
Gotcha, thanks. It wasn't on the roadmap, but it is now!

**Comment by PatrickBRT** [comment]
Hi!
First of: great job you did with cavy! 👍 

While working on some project I was in need of setup/teardown functions, therefore i added those to cavy ( PR: https://github.com/pixielabs/cavy/pull/57 ).

Maybe it's of some use / even can be merged :)

**Comment by jalada** [comment]
`beforeEach` is now in 2.0.0 via #123. If there's any other lifecycle hook you need, please let us know about your particular use-case so we can re-evaluate whether they should be included.
