### ISSUE TITLE
Custom functions before/after tests

### ISSUE THREAD

**Issue by pgonzalez-santiago** [pixielabs/cavy#54]
Hi guys, I am using cavy but I need to set up some custom logs if  the test works or fails. For example I use reactotron to log the data and instead of the common console.log. I think it is a good approach have the possiblity of passing  two functions as parameters to the 'spec.it' function, one for success and one for the fail.

```
export default function(spec) {
  spec.describe('Login', function() {
    spec.it('works', async function() {
      await spec.press('PublicListScreen.LoginButton')
      await spec.fillIn('Scene.Login.Username', 'pedro@pedro.com')
      await spec.fillIn('Scene.Login.Password', 'PedroPedro')
      await spec.press('Scene.Login.Button')
    },
    function() { return console.tron.log(`LOGIN TEST SUCCESS  ✅`) }, //Success function
    function() { return console.tron.log(`LOGIN TEST ERROR  ❌`) }, //Fail function
    )
  })
}
```
I have made this changes in a fork.  https://github.com/pgonzalez-santiago/cavy
you can see my changes in here: https://github.com/pixielabs/cavy/compare/master...pgonzalez-santiago:master

What do you think?

**Comment by jalada** [comment]
This will mostly be covered by https://github.com/pixielabs/cavy/issues/16.

I'd rather have a global configuration option that lets you set an object to use for logging (e.g. instead of `console`, so you could pass in `console.tron`). Feels neater. Thoughts?

**Comment by jalada** [comment]
I'm closing this in favour of the work on the roadmap in #16. If there's anything you think we won't cover for your use case, please let us know.
