### ISSUE TITLE
Change Cavy to a devDependency in the sample app

### ISSUE THREAD

**Issue by victorhazbun** [pixielabs/cavy#55]
https://github.com/pixielabs/cavy/blob/0b6fd5b95a6301b6ed029d93d8cd97170e352df3/sample-app/EmployeeDirectory/package.json#L10

**Comment by jalada** [comment]
No particular reason I guess. We can change it.

**Comment by AbigailMcP** [comment]
Closing - moved Cavy to dev dependency in sample app (PR #60).
