### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by jalada** [pixielabs/cavy#56]
Perhaps based on https://www.contributor-covenant.org/

**Comment by mcdaniel67** [comment]
Was adding the contributor covenant and noticed it had a section for the project team email address. What would be best there? Also is linking it from the first bullet in the contributing section a good place for it?

Branch is here if you want to see how it'd look:
https://github.com/mcdaniel67/cavy/tree/feature__contribution_guide

**Comment by jalada** [comment]
Hi @mcdaniel67. Thanks for helping with our documentation 🙌 

* dev@pixielabs.io is the most suitable email address for this.
* I also suggest making the file name ALL_CAPS.
* I don't think we need to do much more than link to it. Following other adopters for the CC, the copy could read something like 'Before contributing, please read the code of conduct.' with the link.

**Comment by mcdaniel67** [comment]
Sounds good, made all the suggested changes and opened PR https://github.com/pixielabs/cavy/pull/62
