### ISSUE TITLE
Sample App doesn't work with Android.

### ISSUE THREAD

**Issue by joshuapinter** [pixielabs/cavy#58]
Hey Guys, 

Very interested in replacing Appium with Cavy for our Android/RN app but ran into some trouble getting the sample app working on Android. 

If you can update the sample app to make it easier to get up and running, that would be really helpful. Or, if I'm missing something, let me know. 

Thanks!

Joshua

**Comment by AbigailMcP** [comment]
Hey @joshuapinter - thanks for letting us know :)

I've added a couple of fixes in PR #60, which should get the Android app up and working again.

Let me know if you have any other issues!

**Comment by jalada** [comment]
Should be fixed with #60. Let us know if not.
