### ISSUE TITLE
Update documentation for setting up sample app

### ISSUE THREAD

**Issue by jalada** [pixielabs/cavy#64]
As per #60, the sample app README tells you to follow the upstream instructions, but they're a little out of date now. We should do our own instructions.

Whilst we're at it, we could improve some other aspects of the sample app, e.g. replace all the people with types of cavy 😎

**Comment by AbigailMcP** [comment]
Updated in #74 - we've stopped linking to the instructions in the original repo, as that didn't make sense any more.
Closing issue.
