### ISSUE TITLE
Trigger native keyboard search button from a TextInput

### ISSUE THREAD

**Issue by cjcheshire** [pixielabs/cavy#65]
Hey, very new to your library and evaluating if we can use on our project. We have a TextInput that is used to capture a search query.  When done, the user taps the native search button to move to the next screen.

We'd like to trigger the native keyboard search button action once cavy has entered some text.  Something like this:

```
    spec.it('Search for maths', async function () {
      const searchText = 'maths';
      await spec.fillIn('searchText', searchText);
      await spec.submit('searchText');
      await spec.pause(1000);
      //...
    });
```

Submit doesn't exist but is there something we can use?

**Comment by jalada** [comment]
Thanks for trying out Cavy!

When the user taps on the native search button, is there an underlying JS callback function being triggered on a component? That's what you would have to hook into and trigger with Cavy; it lives in React Native so can't trigger anything in the native layer.

Does that make sense?

**Comment by cjcheshire** [comment]
Thanks for getting back to me. Yea that makes sense. In theory though we are bypassing the keyboard that way right?

It’s a good idea and I guess we should expect the native keyboard works but I’m really after simulating the user experience In the spec as much as possible.

**Comment by jalada** [comment]
You're 100% right, it's bypassing the keyboard. If you want to simulate the native interaction then you'll have to use something else other than Cavy, as you need something that has native integration, and you may need to write different test code for different platforms.

Try http://appium.io/ or https://developer.apple.com/documentation/xctest.

**Comment by cjcheshire** [comment]
Again thanks for the support. Funnily enough they are being accessed by other members of the team! Will keep an eye on the library.
