### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mcdaniel67** [pixielabs/cavy#66]
It'd be good to have unit tests running so that we can make code changes confidently. Some decisions would need to be made on the choice of framework and such. I tried it out using jest/travis-ci, but it might be worth considering other alternatives. 

[Branch](https://github.com/mcdaniel67/cavy/tree/feature__travis_unit_tests)

[Travis Build](https://travis-ci.org/mcdaniel67/cavy/builds/303337029)

**Comment by jalada** [comment]
Hi @mcdaniel67, this is great! Happy with Jest as a choice, given that it's the framework _de facto_ for React. Also happy with Travis. We use CircleCI at Pixie Labs but it feels like Travis is more common for open source projects?

Please can you submit your branch as a PR and we'll get it merged in.
