### ISSUE TITLE
Update sample app React Native version

### ISSUE THREAD

**Issue by jalada** [pixielabs/cavy#69]
We know Cavy works with the latest React Native, but we should update our sample-app acordingly.

**Comment by CoreyAR** [comment]
Navigator has been deprecated from RN 0.53.0. What navigation do you think would be most appropriate for the SampleApp? I think `react-navigation` because it is a pure JS solution that is widely in use.

**Comment by AbigailMcP** [comment]
Thanks @CoreyAR! Good spot.
We've updated the sample app so that it uses `react-navigation` in PR #74.
