### ISSUE TITLE
Does not work with Mobx?

### ISSUE THREAD

**Issue by dirkjot** [pixielabs/cavy#71]
I cannot find a mailing list so this goes here for now:  I am working on a react-native project which uses Mobx.  I cannot seem to get Cavy working, but it works fine if I remove Mobx.  The existing code wraps the App with `observer` from `mobx-react/native` ([documentation](https://mobx.js.org/refguide/observer-component.html#-observer)). 

The error I am getting is that `generateTestHook` cannot be found.

Can anybody give me advice on how to combine the two or Is this a known incompatibility?

**Comment by evanmcd** [comment]
I'm interested in this as well, as I am looking at Cavy for testing and use Mobx as well.

**Comment by jalada** [comment]
Thanks both, we're investigating what needs to be done to properly support Mobx, and hope to have something for you soon :)

**Comment by AbigailMcP** [comment]
Hi @dirkjot, @evanmcd ! Apologies - this has taken us a little while to get round to.

I've pulled together a basic RN app using MobX for state management and Cavy for testing. Check out the [example repo](https://github.com/pixielabs/cavy-mobx-example) and let me know if you still have any issues in your specific cases.
