### ISSUE TITLE
Request for screenshot

### ISSUE THREAD

**Issue by hanselsen** [pixielabs/cavy#73]
I would really like to save screenshots for moments in my test suite.

Something like 

```
await spec.screenshot('Login_page');
await spec.fillIn('LoginPage.Email', 'foo@bar.com');
await spec.screenshot('Login_page_filled');
```

After this, I would like to have a folder with these images.  
Is this possible?

**Comment by jalada** [comment]
Thanks @hanselsen! Because Cavy is JavaScript only, we don't really have access to what the app 'looks' like, it would require a native component. We'll keep it in mind for a future version but it's probably outside Cavy's responsibility for now.

**Comment by jalada** [comment]
Note to self: https://github.com/gre/react-native-view-shot

**Comment by jalada** [comment]
@hanselsen in the mean time could you use something like https://github.com/gre/react-native-view-shot in your specs somehow?

**Comment by hanselsen** [comment]
@jalada that was indeed my backup. When I am finished with this, I will share the solution.

**Comment by em-cd** [comment]
hey @hanselsen! did you manage to get this working?

**Comment by hanselsen** [comment]
@em-cd sadly no

**Comment by AbigailMcP** [comment]
Closing this for now as this functionality is not currently on the roadmap for Cavy.
