### ISSUE TITLE
Use navigation props in spec

### ISSUE THREAD

**Issue by papsti7** [pixielabs/cavy#75]
I'm using React Navigation which structures my app in a StackNavigation and a nested TabNavigator.
I want to navigate through the app in one of my specs, but for this I need to dispatch an action to the navigator. 
Usually I call `this.props.navigation`, which - of course - doesn't work out within a spec. 

Has anyone an idea how to get access to the navigation object? 

Is there a way to pass props to a spec?

**Comment by jalada** [comment]
Hi @papsti7! Cavy is an end-to-end framework which means it shouldn't be dispatching actions; you should be tapping on the components that dispatch those actions. Is there an issue that's stopping you from doing that in your app that we can help with?

**Comment by papsti7** [comment]
Thanks for the response @jalada !

I'm not sure if I understand everything correctly, but how should I `generateTestHook('xy')` for the buttons in the tabbar of react navigation? 

Those are generated dynamically by the react navigation library, I just define the screen components and hirarachy.
