### ISSUE TITLE
Wrap function defaultProps as static variable warning

### ISSUE THREAD

**Issue by luizParreira** [pixielabs/cavy#76]
Everytime I use the `wrap` function to wrap some of my functional components into a class, I get this warning on the debugger:
```
Warning: Setting defaultProps as an instance property on Component is not supported and will be ignored. Instead, define defaultProps as a static property on Component.
```
Should we not favour the implementation of a class component with `defaultProps` being a `static` property?

Whenever I use `recompose`'s [`toClass`](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/toClass.js) function, this warning goes away. Considering that `recompose` has already implemented this function, and that you are adding a dependency `create-react-class` to create React classes, wouldn't it be better to use `recompose`'s `toClass` function as the export of the `wrap` function?

Something along these lines:

```js

import {toClass} from 'recompose';

// Public: Wrap a stateless (purely functional) component in a non-stateless
// component so that a `ref` can be added.
//
// For example, the react-native-elements <Button /> is purely functional, so
// a ref cannot be assigned and thus it cannot be added to your Cavy test hook
// store.
//
// statelessComponent - The purely functional React component you want to wrap.
//
// Example
//
//   import {
//     Button
//   } from 'react-native-elements';
//   import { wrap } from 'cavy';
//
//   class MyComponent extends React.Component {
//     // ...
//     render() {
//       const wrappedButton = wrap(Button);
//
//       // ...
//     }
//   }

export default toClass;
```

**Comment by luizParreira** [comment]
I have create a PR that would fix such a warning for the `wrap` function of cavy, by using recompose's `toClass` function. https://github.com/pixielabs/cavy/pull/77

**Comment by jalada** [comment]
Thanks for this work! We'll get this in the next release.

**Comment by jalada** [comment]
Closing as per #77. We'll remove `wrap` completely in version 1.0.0.
