### ISSUE TITLE
Show 'A component for xxxx has already been registered. Overwriting.' warning message.

### ISSUE THREAD

**Issue by Kennytian** [pixielabs/cavy#84]
Repeatedly entry detail page and go back to home page, will show warnning message.

![stack](https://user-images.githubusercontent.com/2621619/38195662-302fe7a4-3644-11e8-90d1-790fc89e7380.gif)

**Comment by johnmarinelli** [comment]
From https://github.com/pixielabs/cavy/pull/86:

@jalada @Kennytian I also noticed this issue, and tried for a little while to hack together a log message verbosity setting Cavy that could control this.   

However, it looks like it's already [built in to React Native](https://facebook.github.io/react-native/docs/debugging.html#warnings) (as of 0.52 at least).  You can disable warnings individually, or as a whole.  

The lines that I used were:

```
import { YellowBox } from 'cavy'
YellowBox.ignoreWarnings(['A component for'])
```

The fact that the YellowBox api only checks for message prefixes is slightly annoying, though.  Maybe npm packages for rn should use prefixes for the yellow/red box messages ¯\_(ツ)_/¯ either way the issue has been resolved for me.

**Comment by em-cd** [comment]
hey @Kennytian and @johnmarinelli! did #96 resolve this, so we can close this issue?

**Comment by Kennytian** [comment]
@jalada  @em-cd  Thanks for your good work!
