### ISSUE TITLE
How can i press ‘return' key?

### ISSUE THREAD

**Issue by keerthivasanvsdet** [pixielabs/cavy#87]
Thanks for building this, I use this in my project. I want to press on the ‘return’ key in keyboard using cavy? Is it possible?

Tried await spec.press(‘return’); which doesn’t seem to work.

**Comment by AbigailMcP** [comment]
Hi @keerthivasanvsdet - thanks for using Cavy!

Cavy lives in React Native, so you won't be able to trigger a native keyboard press. Is there an underlying JS callback function bring triggered when the return key is pressed?

If so, you can use Cavy to find the component in question (using `await spec.findComponent('identifier')`) and trigger the function on the component in your Cavy tests.

Hope that makes sense!

**Comment by keerthivasanvsdet** [comment]
Hi @AbigailMcP - Thanks a lot for your response.

Yes, spec.findComponent works and there is a JS call back function as well when the return key is pressed but how do i trigger the function on the component using cavy? Is there a specific syntax to it?

**Comment by AbigailMcP** [comment]
Hi @keerthivasanvsdet - If you can find the component with `spec.findComponent`, then you can call the function directly on the returned component.

Something like this:
```
const component = await spec.findComponent('identifier');
component.someFunction();
```

Hope that helps!
