### ISSUE TITLE
A component for <Component Name> has already been registered. Overwriting.

### ISSUE THREAD

**Issue by elyran** [pixielabs/cavy#92]
Hi, thanks for cavy!

I'm getting this warning:
A component for <Component Name> has already been registered. Overwriting.

Looking at the source code:
https://github.com/pixielabs/cavy/blob/171df092ae603dc3f8286959fb3428d32dbe9e3f/src/TestHookStore.js
It looks like the issue is about re-render().

I have this component:
`<StartButton ref={this.props.generateTestHook('Home.StartButton')} onPress={this.onPressStart} />`
When its container `View` re-renders, it calls `this.props.generateTestHook()` again.

Any idea on how to fix this?

**Comment by AbigailMcP** [comment]
Hi @elyran - thanks for using Cavy!

Overwriting the existing component in this context is the expected behaviour. We're actually thinking of removing this warning (as it's a little misleading) and including it as a debug message only.

(See comment on PR #85 )

**Comment by jalada** [comment]
@elyran firstly, re: PR #85. Yes, that's what my comment on it points out too.

Secondly, we're working on improving the `generateTestHook` API :) and it's along these kinds of lines! See the discussion in https://github.com/pixielabs/cavy/pull/78

**Comment by elyran** [comment]
Wasn't aware of #78 . Great!
