### ISSUE TITLE
Tests starts when app is loaded

### ISSUE THREAD

**Issue by fzymek** [pixielabs/cavy#94]
Tests starts whenever app is loaded/reloaded. 
Here's my root component:

```
export default class App extends Component<Props, State> {
  render() {
    return (
      <Tester specs={[AppSpec]} store={testHookStore} waitTime={2000} sendReport={true}>
        <RootStack />
      </Tester>
    );
  }
}
```

Now, whenever I try to reload the app while developing components, tests are executed. This makes it really hard to develop/manually test app when developing features and components.

**Comment by AbigailMcP** [comment]
Hey @fzymek , thanks for getting in touch.

Yep, you're right - this is definitely something on our radar.

There's an open issue for this here #1 - which  links to an example of how other people are disabling testing when the app loads.
